---
title: "DESeq2_time"
author: "Leticia"
date: "18/01/2022"
output:
  html_document: 
    toc: true
    toc_depth: 4
---
## Aim

Using the DESeq2 package to detect developmental sex-biased genes.

## Libraries and functions

```{r, message=FALSE, warning=FALSE}
setwd("~/R_analyses/280622_SB_repo/Sex_bias_manuscript/Calling_SB_genes")

library(DESeq2)
library(gplots)
library(readr)
library(dplyr)

metadata_dir <- "../Metadata/"
counts_dir <- "../Norm_counts/"
raw_counts_dir <- "../Raw_counts/"

#Function for preparing data for DESEq2. sp= species; ts= tissue.
prepro_data_DESeq2 <- function(sp, ts){
  # Loading counts and metadata from the species
  meta_sp<- read_csv(paste0(metadata_dir, sp, ".sampleTable.csv"))
  counts_sp <- as.matrix(read.table(gzfile(paste0(raw_counts_dir, sp, "_counts_alltp.txt.gz")),header = TRUE))
  
  norm_counts_sp <- read.csv(paste0(counts_dir, sp, "CountsMajorTissuesCor90.Norm.txt"), row.names=1, sep="")
  
  # Getting log2 cpm
  norm_counts_sp_log <- as.matrix(log2(norm_counts_sp+1))
  
  # Subsetting metadata by organ 
  meta_sp_ts <- subset(meta_sp, tissue==ts)
    
  #Filtering time points where we don't have males or females and adding numbers to the replicates
  meta_sp_ts %>% group_by(timePoint) %>% summarise(femCount = sum(sex == "Female"), maleCount = sum(sex == "Male"))%>% filter(femCount != 0 & maleCount != 0)%>% dplyr::select(timePoint)->use_tp
  meta_sp_ts_filt <- subset(meta_sp_ts, timePoint %in% use_tp$timePoint)
    
  # Subsetting counts organ  
  counts_sp_ts <-counts_sp[,as.character(meta_sp_ts_filt$id)]
  
  # Filtering out genes that are expressed in less than 3 samples
  norm_counts_sp_log_ts <- norm_counts_sp_log[,c(as.character(meta_sp_ts_filt$id))]
  norm_counts_sp_log_ts_filt <- norm_counts_sp_log_ts[rowSums(norm_counts_sp_log_ts != 0) > 2, ]
  counts_sp_ts_filt <- counts_sp_ts[(rownames(counts_sp_ts) %in% rownames(norm_counts_sp_log_ts_filt)), ]

  return(list(meta_sp_ts_filt, counts_sp_ts_filt))
}

#Function for performing differential expression analysis and likelihod ratio test. counts_ts= preprocessed counts for 1 species and 1 tissue; meta_ts= preprocessed metadata for 1 species and 1 tissue.
DESeq_calls <- function(counts_ts, meta_ts){
  # Making sure that the columns in the count matrix are in the right order
  rownames(meta_ts) <- as.character(meta_ts$id)
  counts_ts <- counts_ts[, rownames(meta_ts)]
  
  # Setting time points to start in 0
  tp_table <- as.data.frame(table(meta_ts$timePoint))
  meta_ts$new_timePoint <- rep(0:(nrow(tp_table)-1), tp_table$Freq)
  
  # Creating the matrix with our factors of interest (sex and time)
  designMatrix <- data.frame(sex=meta_ts$sex,time=meta_ts$new_timePoint)
  
  # Constructing the DESeqDataSet
  dds <- DESeqDataSetFromMatrix(countData = counts_ts, colData = designMatrix, design = ~sex + time + sex:time)
  
  # Performing the main computation
  dds <- DESeq(dds)
  
  # Likelihood ratio test
  ddsLRT <- nbinomLRT(dds, reduced = ~time)
  resLRT <- as.data.frame(results(ddsLRT))
  
  return(resLRT)
}
```

## Running pipeline

```{r, message=FALSE, warning=FALSE}
dir.create("DESeq_time_res")
res_dir <- "DESeq_time_res/"

species <- c("Human", "Mouse", "Rat", "Rabbit", "Opossum", "Chicken")
tissues <- c("Brain", "Cerebellum", "Heart", "Kidney", "Liver")

results <- list()

for (sp in species){
  for (ts in tissues){
    sp_meta_ts <-prepro_data_DESeq2(sp, ts)[[1]]
    sp_counts_ts<-prepro_data_DESeq2(sp, ts)[[2]]
    DESeq_res <- DESeq_calls(sp_counts_ts, sp_meta_ts)
    results[[paste0(sp, "_", ts)]] <- DESeq_res

    # Exporting results
    write.table(DESeq_res, sep="\t", file=paste0(res_dir, sp, "_", ts, ".txt"), quote=FALSE)
  }
}
```

