---
title: "maSigPro"
author: "Leticia"
date: "18/01/2022"
output:
  html_document: 
    toc: true
    toc_depth: 4
---
## Aim

Using the maSigPro package to detect developmental sex-biased genes.

```{r}
library(maSigPro)
library(readr)

metadata_dir <- "../metadata/"
counts_dir <- "../counts/"

#Function for preparing data for maSigPro. sp= species; ts= tissue.
prepro_data_maSigPro <- function(sp, ts){
  # Loading counts and metadata from the species
  meta_sp<- read_csv(paste0(metadata_dir, sp, ".sampleTable.csv"))
  counts_sp <- read.csv(paste0(counts_dir, sp, "CountsMajorTissuesCor90.Norm.txt"), row.names=1, sep="")

  #Getting log2 cpm
  counts_sp_log <- as.matrix(log2(counts_sp+1))
  
  # Subsetting metadata organ
  meta_sp_ts <- subset(meta_sp, tissue==ts)
    
  #Filtering time points where we don't have males or females and adding numbers to the replicates
  meta_sp_ts %>% group_by(timePoint) %>% summarise(femCount = sum(sex == "Female"), maleCount = sum(sex == "Male"))%>% filter(femCount != 0 & maleCount != 0)%>% dplyr::select(timePoint)->use_tp
  meta_sp_ts_filt <- subset(meta_sp_ts, timePoint %in% use_tp$timePoint)
  
  # Subsetting counts organ 
  counts_sp_ts <-counts_sp[,as.character(meta_sp_ts_filt$id)]
  
  # Filtering out genes that are expressed in less than 3 samples
  counts_sp_log_ts <- counts_sp_log[,c(as.character(meta_sp_ts_filt$id))]
  counts_sp_log_ts_filt <- counts_sp_log_ts[rowSums(counts_sp_log_ts != 0) > 2, ]
    
  counts_sp_ts_filt <- counts_sp_ts[(rownames(counts_sp_ts) %in% rownames(counts_sp_log_ts_filt)), ]
  
  return(list(meta_sp_ts_filt, counts_sp_ts_filt))
}

#Function for performing differential expression analysis with MaSigPro. counts_ts= preprocessed counts for 1 species and 1 tissue; meta_ts= preprocessed metadata for 1 species and 1 tissue.
maSigPro_DE <- function(counts_ts, meta_ts){
  # Making sure that the columns in the count matrix are in the right order
  rownames(meta_ts) <- as.character(meta_ts$id)
  counts_ts <- counts_ts[, rownames(meta_ts)]
  
  # Setting time points to start in 0
  tp_table <- as.data.frame(table(meta_ts$timePoint))
  meta_ts$new_timePoint <- rep(0:(nrow(tp_table)-1), tp_table$Freq)
  
  # Getting the numbers for the replicates
  reps <- as.data.frame(table(paste0(letters[meta_ts$new_timePoint+1], meta_ts$sex)))
  
  # Creating the design table
  df_design <- data.frame(Time=meta_ts$new_timePoint,Replicate = rep(1:length(reps$Var1), times=reps$Freq), Male=ifelse(meta_ts$sex=="Male", 1, 0) , Female=ifelse(meta_ts$sex=="Female", 1, 0), row.names=meta_ts$id)
  design <- make.design.matrix(df_design, degree=2) 
  
  # Getting differentially expressed genes
  NBp <- p.vector (counts_ts, design, counts=TRUE)
  NBt <- T.fit(NBp, alfa = 0.05)
  res<-get.siggenes(NBt, vars="groups")
  DE_genes <- res$sig.genes$FemalevsMale$sig.pvalues
  DE_genes_0.05 <-subset(DE_genes, DE_genes$`p-value` <0.05)
  
  # Removing potential outliers
  influ_genes<-colnames(NBt$influ.info)
  DE_genes_filt <-subset(DE_genes_0.05, !rownames(DE_genes_0.05) %in% influ_genes)
  
  
  return(DE_genes_filt)
}
```

## Running pipeline

```{r, message=FALSE, warning=FALSE}
res_dir <- "MaSigPro_res_cpm/"

species <- c("Human", "Mouse", "Rat", "Rabbit","Opossum", "Chicken")
tissues <-  c("Brain", "Cerebellum", "Heart", "Kidney", "Liver")

species <- "Mouse"
tissues <- "Brain"

results <- list()

for (sp in species){
  for (ts in tissues){
    sp_meta_ts <-prepro_data_maSigPro(sp, ts)[[1]]
    sp_counts_ts<-prepro_data_maSigPro(sp, ts)[[2]]
    maSigPro_res <- maSigPro_DE(sp_counts_ts, sp_meta_ts)
    results[[paste0(sp, "_", ts)]] <- maSigPro_res
    # Exporting results
    # write.table(maSigPro_res, sep="\t", file=paste0(res_dir, sp, "_", ts, ".txt"), quote=FALSE)
  }
}
```